<?php
/**
*Implementation of hook_form_alter
*Implementing hook_theme().
*/
function ticket_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form_id == 'comment_comment_form') {
        $form['actions']['submit']['#value'] = t('Comment');
    }
}

function ticket_theme($existing, $type, $theme, $path) {
    return [
      'template' => [
          'variables' => array('nodes' => array(), 'title' => ''),
       ],
      'node__ticket' => [
        'template' => 'node--ticket',
        'base hook' => 'node'
      ],
    ]; 
  }